version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/Users/eblack/script/docker/dev/fourth-meal-wp/data/mysql
       - /Users/eblack/script/docker/dev/fourth-meal-wp/data/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     volumes:
       - /Users/eblack/script/docker/dev/fourth-meal-wp/data/html:/var/www/html
     image: wordpress:latest
     ports:
       - "8500:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
